# Generated by Django 4.1.7 on 2023-02-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0004_movieorder_movie_movie_users"),
        ("users", "0002_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_movies",
            field=models.ManyToManyField(
                related_name="users_movies",
                through="movies.MovieOrder",
                to="movies.movie",
            ),
        ),
    ]
