# Generated by Django 4.1.7 on 2023-02-20 19:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0004_movieorder_movie_movie_users"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movieorder",
            old_name="movies_user",
            new_name="movies",
        ),
        migrations.RenameField(
            model_name="movieorder",
            old_name="users_movie",
            new_name="users",
        ),
    ]
