# Generated by Django 4.1.7 on 2023-02-20 21:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("movies", "0005_rename_movies_user_movieorder_movies_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="movie_users",
            field=models.ManyToManyField(
                null=True,
                related_name="movie_user",
                through="movies.MovieOrder",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
